version: '3.9'

services:
  python:
    # command: python3 /root/code/app.py
    image: noppawee/ait-nlp-python:v2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: python.Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - .vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
      
  mlflow:
    image: noppawee/ait-nlp-mlflow:v2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000